export const db = {
  anklets: [],
  bracelets: [
    {
      name: "bracelets",
      image: "../../assets/bracelet/1/bracelet_16_1080w.jpg",
      finish: "18K Gold",
      images: [
        "../../assets/bracelet/1/bracelet_14_1080w.jpg",
        "../../assets/bracelet/1/bracelet_15_1080w.jpg",
        "../../assets/bracelet/1/bracelet_16_1080w.jpg",
      ],
      images_thumb: [
        "../../assets/bracelet/1/bracelet_14_360w.jpg",
        "../../assets/bracelet/1/bracelet_15_360w.jpg",
        "../../assets/bracelet/1/bracelet_16_360w.jpg",
      ],
      description: "Tree in the garden serenity ",
      description_details:
        "Moon by Sassyness Introducing our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets, where luxury meets durability. These exquisite bracelets are meticulously crafted to elevate your style with their timeless elegance and superior quality. Each bracelet is meticulously designed using high-grade 18k gold stainless steel, known for its exceptional resistance to tarnish and corrosion. With our anti-tarnish technology, your bracelet will maintain its stunning shine and brilliance, ensuring a long-lasting, lustrous appearance. Crafted with meticulous attention to detail, these bracelets showcase a refined and classy design that effortlessly complements any outfit. The sleek and polished surfaces exude sophistication, making them the perfect accessory for both formal occasions and everyday wear. Our premium 18k gold stainless steel material not only offers exceptional durability but also provides a hypoallergenic and skin-friendly option for those with sensitive skin. You can wear these bracelets with confidence, knowing they will withstand the test of time and maintain their exquisite beauty. The secure clasp ensures a comfortable and secure fit, allowing you to wear these bracelets with ease and confidence throughout the day. Whether you're attending a special event or adding a touch of elegance to your everyday ensemble, these bracelets are designed to make a statement. Experience the perfect combination of luxury and practicality with our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets. Indulge in the sophistication and enduring beauty that comes with wearing premium quality jewelry. Elevate your accessory collection with these timeless bracelets, designed to be cherished for years to come.",
      description_list: [
        "Pure 18K Gold Plated",
        "Premium Quality Stainless Steel Base Metal",
        "Hypoallergenic, Lead & Nickel Free",
        "Anti-tarnish & Waterproof",
      ],
    },
    {
      name: "bracelets",
      image: "../../assets/bracelet/2/bracelet_22_1080w.jpg",
      finish: "18K Gold",
      images: [
        "../../assets/bracelet/2/bracelet_17_1080w.jpg",
        "../../assets/bracelet/2/bracelet_18_1080w.jpg",
        "../../assets/bracelet/2/bracelet_19_1080w.jpg",
        "../../assets/bracelet/2/bracelet_20_1080w.jpg",
        "../../assets/bracelet/2/bracelet_21_1080w.jpg",
        "../../assets/bracelet/2/bracelet_22_1080w.jpg",
      ],
      images_thumb: [
        "../../assets/bracelet/2/bracelet_17_360w.jpg",
        "../../assets/bracelet/2/bracelet_18_360w.jpg",
        "../../assets/bracelet/2/bracelet_19_360w.jpg",
        "../../assets/bracelet/2/bracelet_20_360w.jpg",
        "../../assets/bracelet/2/bracelet_21_360w.jpg",
        "../../assets/bracelet/2/bracelet_22_360w.jpg",
      ],
      description: "Bending like bangle",
      description_details:
        "Moon by Sassyness Introducing our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets, where luxury meets durability. These exquisite bracelets are meticulously crafted to elevate your style with their timeless elegance and superior quality. Each bracelet is meticulously designed using high-grade 18k gold stainless steel, known for its exceptional resistance to tarnish and corrosion. With our anti-tarnish technology, your bracelet will maintain its stunning shine and brilliance, ensuring a long-lasting, lustrous appearance. Crafted with meticulous attention to detail, these bracelets showcase a refined and classy design that effortlessly complements any outfit. The sleek and polished surfaces exude sophistication, making them the perfect accessory for both formal occasions and everyday wear. Our premium 18k gold stainless steel material not only offers exceptional durability but also provides a hypoallergenic and skin-friendly option for those with sensitive skin. You can wear these bracelets with confidence, knowing they will withstand the test of time and maintain their exquisite beauty. The secure clasp ensures a comfortable and secure fit, allowing you to wear these bracelets with ease and confidence throughout the day. Whether you're attending a special event or adding a touch of elegance to your everyday ensemble, these bracelets are designed to make a statement. Experience the perfect combination of luxury and practicality with our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets. Indulge in the sophistication and enduring beauty that comes with wearing premium quality jewelry. Elevate your accessory collection with these timeless bracelets, designed to be cherished for years to come.",
      description_list: [
        "Pure 18K Gold Plated",
        "Premium Quality Stainless Steel Base Metal",
        "Hypoallergenic, Lead & Nickel Free",
        "Anti-tarnish & Waterproof",
      ],
    },
    {
      name: "bracelets",
      image: "../../assets/bracelet/3/bracelet_30_1080w.jpg",
      finish: "18K Gold",
      images: [
        "../../assets/bracelet/3/bracelet_24_1080w.jpg",
        "../../assets/bracelet/3/bracelet_25_1080w.jpg",
        "../../assets/bracelet/3/bracelet_26_1080w.jpg",
        "../../assets/bracelet/3/bracelet_27_1080w.jpg",
        "../../assets/bracelet/3/bracelet_28_1080w.jpg",
        "../../assets/bracelet/3/bracelet_29_1080w.jpg",
        "../../assets/bracelet/3/bracelet_30_1080w.jpg",
      ],
      images_thumb: [
        "../../assets/bracelet/3/bracelet_24_360w.jpg",
        "../../assets/bracelet/3/bracelet_25_360w.jpg",
        "../../assets/bracelet/3/bracelet_26_360w.jpg",
        "../../assets/bracelet/3/bracelet_27_360w.jpg",
        "../../assets/bracelet/3/bracelet_28_360w.jpg",
        "../../assets/bracelet/3/bracelet_29_360w.jpg",
        "../../assets/bracelet/3/bracelet_30_360w.jpg",
      ],
      description: "Triple Pearl square",
      description_details:
        "Moon by Sassyness Introducing our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets, where luxury meets durability. These exquisite bracelets are meticulously crafted to elevate your style with their timeless elegance and superior quality. Each bracelet is meticulously designed using high-grade 18k gold stainless steel, known for its exceptional resistance to tarnish and corrosion. With our anti-tarnish technology, your bracelet will maintain its stunning shine and brilliance, ensuring a long-lasting, lustrous appearance. Crafted with meticulous attention to detail, these bracelets showcase a refined and classy design that effortlessly complements any outfit. The sleek and polished surfaces exude sophistication, making them the perfect accessory for both formal occasions and everyday wear. Our premium 18k gold stainless steel material not only offers exceptional durability but also provides a hypoallergenic and skin-friendly option for those with sensitive skin. You can wear these bracelets with confidence, knowing they will withstand the test of time and maintain their exquisite beauty. The secure clasp ensures a comfortable and secure fit, allowing you to wear these bracelets with ease and confidence throughout the day. Whether you're attending a special event or adding a touch of elegance to your everyday ensemble, these bracelets are designed to make a statement. Experience the perfect combination of luxury and practicality with our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets. Indulge in the sophistication and enduring beauty that comes with wearing premium quality jewelry. Elevate your accessory collection with these timeless bracelets, designed to be cherished for years to come.",
      description_list: [
        "Pure 18K Gold Plated",
        "Premium Quality Stainless Steel Base Metal",
        "Hypoallergenic, Lead & Nickel Free",
        "Anti-tarnish & Waterproof",
      ],
    },
    {
      name: "bracelets",
      image: "../../assets/bracelet/4/bracelet_35_1080w.jpg",
      finish: "18K Gold",
      images: [
        "../../assets/bracelet/4/bracelet_32_1080w.jpg",
        "../../assets/bracelet/4/bracelet_33_1080w.jpg",
        "../../assets/bracelet/4/bracelet_34_1080w.jpg",
        "../../assets/bracelet/4/bracelet_35_1080w.jpg",
      ],
      images_thumb: [
        "../../assets/bracelet/4/bracelet_32_360w.jpg",
        "../../assets/bracelet/4/bracelet_33_360w.jpg",
        "../../assets/bracelet/4/bracelet_34_360w.jpg",
        "../../assets/bracelet/4/bracelet_35_360w.jpg",
      ],
      description: "Butterfly in 3D",
      description_details:
        "Moon by Sassyness Introducing our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets, where luxury meets durability. These exquisite bracelets are meticulously crafted to elevate your style with their timeless elegance and superior quality. Each bracelet is meticulously designed using high-grade 18k gold stainless steel, known for its exceptional resistance to tarnish and corrosion. With our anti-tarnish technology, your bracelet will maintain its stunning shine and brilliance, ensuring a long-lasting, lustrous appearance. Crafted with meticulous attention to detail, these bracelets showcase a refined and classy design that effortlessly complements any outfit. The sleek and polished surfaces exude sophistication, making them the perfect accessory for both formal occasions and everyday wear. Our premium 18k gold stainless steel material not only offers exceptional durability but also provides a hypoallergenic and skin-friendly option for those with sensitive skin. You can wear these bracelets with confidence, knowing they will withstand the test of time and maintain their exquisite beauty. The secure clasp ensures a comfortable and secure fit, allowing you to wear these bracelets with ease and confidence throughout the day. Whether you're attending a special event or adding a touch of elegance to your everyday ensemble, these bracelets are designed to make a statement. Experience the perfect combination of luxury and practicality with our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets. Indulge in the sophistication and enduring beauty that comes with wearing premium quality jewelry. Elevate your accessory collection with these timeless bracelets, designed to be cherished for years to come.",
      description_list: [
        "Pure 18K Gold Plated",
        "Premium Quality Stainless Steel Base Metal",
        "Hypoallergenic, Lead & Nickel Free",
        "Anti-tarnish & Waterproof",
      ],
    },
    {
      name: "bracelets",
      image: "../../assets/bracelet/5/bracelet_39_1080w.jpg",
      finish: "18K Gold",
      images: [
        "../../assets/bracelet/5/bracelet_37_1080w.jpg",
        "../../assets/bracelet/5/bracelet_38_1080w.jpg",
        "../../assets/bracelet/5/bracelet_39_1080w.jpg",
      ],
      images_thumb: [
        "../../assets/bracelet/5/bracelet_37_360w.jpg",
        "../../assets/bracelet/5/bracelet_38_360w.jpg",
        "../../assets/bracelet/5/bracelet_39_360w.jpg",
      ],
      description: "Blooming black petal in Gold",
      description_details:
        "Moon by Sassyness Introducing our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets, where luxury meets durability. These exquisite bracelets are meticulously crafted to elevate your style with their timeless elegance and superior quality. Each bracelet is meticulously designed using high-grade 18k gold stainless steel, known for its exceptional resistance to tarnish and corrosion. With our anti-tarnish technology, your bracelet will maintain its stunning shine and brilliance, ensuring a long-lasting, lustrous appearance. Crafted with meticulous attention to detail, these bracelets showcase a refined and classy design that effortlessly complements any outfit. The sleek and polished surfaces exude sophistication, making them the perfect accessory for both formal occasions and everyday wear. Our premium 18k gold stainless steel material not only offers exceptional durability but also provides a hypoallergenic and skin-friendly option for those with sensitive skin. You can wear these bracelets with confidence, knowing they will withstand the test of time and maintain their exquisite beauty. The secure clasp ensures a comfortable and secure fit, allowing you to wear these bracelets with ease and confidence throughout the day. Whether you're attending a special event or adding a touch of elegance to your everyday ensemble, these bracelets are designed to make a statement. Experience the perfect combination of luxury and practicality with our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets. Indulge in the sophistication and enduring beauty that comes with wearing premium quality jewelry. Elevate your accessory collection with these timeless bracelets, designed to be cherished for years to come.",
      description_list: [
        "Pure 18K Gold Plated",
        "Premium Quality Stainless Steel Base Metal",
        "Hypoallergenic, Lead & Nickel Free",
        "Anti-tarnish & Waterproof",
      ],
    },
    {
      name: "bracelets",
      image: "../../assets/bracelet/6/bracelet_44_1080w.jpg",
      finish: "18K Gold",
      images: [
        "../../assets/bracelet/6/bracelet_41_1080w.jpg",
        "../../assets/bracelet/6/bracelet_42_1080w.jpg",
        "../../assets/bracelet/6/bracelet_43_1080w.jpg",
        "../../assets/bracelet/6/bracelet_44_1080w.jpg",
      ],
      images_thumb: [
        "../../assets/bracelet/6/bracelet_41_360w.jpg",
        "../../assets/bracelet/6/bracelet_42_360w.jpg",
        "../../assets/bracelet/6/bracelet_43_360w.jpg",
        "../../assets/bracelet/6/bracelet_44_360w.jpg",
      ],
      description: "Elegant in Pink",
      description_details:
        "Moon by Sassyness Introducing our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets, where luxury meets durability. These exquisite bracelets are meticulously crafted to elevate your style with their timeless elegance and superior quality. Each bracelet is meticulously designed using high-grade 18k gold stainless steel, known for its exceptional resistance to tarnish and corrosion. With our anti-tarnish technology, your bracelet will maintain its stunning shine and brilliance, ensuring a long-lasting, lustrous appearance. Crafted with meticulous attention to detail, these bracelets showcase a refined and classy design that effortlessly complements any outfit. The sleek and polished surfaces exude sophistication, making them the perfect accessory for both formal occasions and everyday wear. Our premium 18k gold stainless steel material not only offers exceptional durability but also provides a hypoallergenic and skin-friendly option for those with sensitive skin. You can wear these bracelets with confidence, knowing they will withstand the test of time and maintain their exquisite beauty. The secure clasp ensures a comfortable and secure fit, allowing you to wear these bracelets with ease and confidence throughout the day. Whether you're attending a special event or adding a touch of elegance to your everyday ensemble, these bracelets are designed to make a statement. Experience the perfect combination of luxury and practicality with our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets. Indulge in the sophistication and enduring beauty that comes with wearing premium quality jewelry. Elevate your accessory collection with these timeless bracelets, designed to be cherished for years to come.",
      description_list: [
        "Pure 18K Gold Plated",
        "Premium Quality Stainless Steel Base Metal",
        "Hypoallergenic, Lead & Nickel Free",
        "Anti-tarnish & Waterproof",
      ],
    },
    {
      name: "bracelets",
      image: "../../assets/bracelet/7/bracelet_49_1080w.jpg",
      finish: "Silver",
      images: [
        "../../assets/bracelet/7/bracelet_46_1080w.jpg",
        "../../assets/bracelet/7/bracelet_47_1080w.jpg",
        "../../assets/bracelet/7/bracelet_48_1080w.jpg",
        "../../assets/bracelet/7/bracelet_49_1080w.jpg",
      ],
      images_thumb: [
        "../../assets/bracelet/7/bracelet_46_360w.jpg",
        "../../assets/bracelet/7/bracelet_47_360w.jpg",
        "../../assets/bracelet/7/bracelet_48_360w.jpg",
        "../../assets/bracelet/7/bracelet_49_360w.jpg",
      ],
      description: "Bending like bangle - Crystal Silver",
      description_details:
        "Moon by Sassyness Introducing our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets, where luxury meets durability. These exquisite bracelets are meticulously crafted to elevate your style with their timeless elegance and superior quality. Each bracelet is meticulously designed using high-grade 18k gold stainless steel, known for its exceptional resistance to tarnish and corrosion. With our anti-tarnish technology, your bracelet will maintain its stunning shine and brilliance, ensuring a long-lasting, lustrous appearance. Crafted with meticulous attention to detail, these bracelets showcase a refined and classy design that effortlessly complements any outfit. The sleek and polished surfaces exude sophistication, making them the perfect accessory for both formal occasions and everyday wear. Our premium 18k gold stainless steel material not only offers exceptional durability but also provides a hypoallergenic and skin-friendly option for those with sensitive skin. You can wear these bracelets with confidence, knowing they will withstand the test of time and maintain their exquisite beauty. The secure clasp ensures a comfortable and secure fit, allowing you to wear these bracelets with ease and confidence throughout the day. Whether you're attending a special event or adding a touch of elegance to your everyday ensemble, these bracelets are designed to make a statement. Experience the perfect combination of luxury and practicality with our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets. Indulge in the sophistication and enduring beauty that comes with wearing premium quality jewelry. Elevate your accessory collection with these timeless bracelets, designed to be cherished for years to come.",
      description_list: [
        "Pure 18K Gold Plated",
        "Premium Quality Stainless Steel Base Metal",
        "Hypoallergenic, Lead & Nickel Free",
        "Anti-tarnish & Waterproof",
      ],
    },
    {
      name: "bracelets",
      image: "../../assets/bracelet/8/bracelet_53_1080w.jpg",
      finish: "18K Gold",
      images: [
        "../../assets/bracelet/8/bracelet_51_1080w.jpg",
        "../../assets/bracelet/8/bracelet_52_1080w.jpg",
        "../../assets/bracelet/8/bracelet_53_1080w.jpg",
      ],
      images_thumb: [
        "../../assets/bracelet/8/bracelet_51_360w.jpg",
        "../../assets/bracelet/8/bracelet_52_360w.jpg",
        "../../assets/bracelet/8/bracelet_53_360w.jpg",
      ],
      description: "Black and white Crystal ",
      description_details:
        "Moon by Sassyness Introducing our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets, where luxury meets durability. These exquisite bracelets are meticulously crafted to elevate your style with their timeless elegance and superior quality. Each bracelet is meticulously designed using high-grade 18k gold stainless steel, known for its exceptional resistance to tarnish and corrosion. With our anti-tarnish technology, your bracelet will maintain its stunning shine and brilliance, ensuring a long-lasting, lustrous appearance. Crafted with meticulous attention to detail, these bracelets showcase a refined and classy design that effortlessly complements any outfit. The sleek and polished surfaces exude sophistication, making them the perfect accessory for both formal occasions and everyday wear. Our premium 18k gold stainless steel material not only offers exceptional durability but also provides a hypoallergenic and skin-friendly option for those with sensitive skin. You can wear these bracelets with confidence, knowing they will withstand the test of time and maintain their exquisite beauty. The secure clasp ensures a comfortable and secure fit, allowing you to wear these bracelets with ease and confidence throughout the day. Whether you're attending a special event or adding a touch of elegance to your everyday ensemble, these bracelets are designed to make a statement. Experience the perfect combination of luxury and practicality with our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets. Indulge in the sophistication and enduring beauty that comes with wearing premium quality jewelry. Elevate your accessory collection with these timeless bracelets, designed to be cherished for years to come.",
      description_list: [
        "Pure 18K Gold Plated",
        "Premium Quality Stainless Steel Base Metal",
        "Hypoallergenic, Lead & Nickel Free",
        "Anti-tarnish & Waterproof",
      ],
    },
  ],
  earrings: [
    {
      name: "earrings",
      image: "../../assets/earrings/1/earrings_60_1080w.jpg",
      finish: "Silver",
      images: [
        "../../assets/earrings/1/earrings_55_1080w.jpg",
        "../../assets/earrings/1/earrings_56_1080w.jpg",
        "../../assets/earrings/1/earrings_57_1080w.jpg",
        "../../assets/earrings/1/earrings_58_1080w.jpg",
        "../../assets/earrings/1/earrings_59_1080w.jpg",
        "../../assets/earrings/1/earrings_60_1080w.jpg",
      ],
      images_thumb: [
        "../../assets/earrings/1/earrings_55_360w.jpg",
        "../../assets/earrings/1/earrings_56_360w.jpg",
        "../../assets/earrings/1/earrings_57_360w.jpg",
        "../../assets/earrings/1/earrings_58_360w.jpg",
        "../../assets/earrings/1/earrings_59_360w.jpg",
        "../../assets/earrings/1/earrings_60_360w.jpg",
      ],
      description: "Crystal Pyramid in Silver",
      description_details:
        "Moon by Sassyness Introducing our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets, where luxury meets durability. These exquisite bracelets are meticulously crafted to elevate your style with their timeless elegance and superior quality. Each bracelet is meticulously designed using high-grade 18k gold stainless steel, known for its exceptional resistance to tarnish and corrosion. With our anti-tarnish technology, your bracelet will maintain its stunning shine and brilliance, ensuring a long-lasting, lustrous appearance. Crafted with meticulous attention to detail, these bracelets showcase a refined and classy design that effortlessly complements any outfit. The sleek and polished surfaces exude sophistication, making them the perfect accessory for both formal occasions and everyday wear. Our premium 18k gold stainless steel material not only offers exceptional durability but also provides a hypoallergenic and skin-friendly option for those with sensitive skin. You can wear these bracelets with confidence, knowing they will withstand the test of time and maintain their exquisite beauty. The secure clasp ensures a comfortable and secure fit, allowing you to wear these bracelets with ease and confidence throughout the day. Whether you're attending a special event or adding a touch of elegance to your everyday ensemble, these bracelets are designed to make a statement. Experience the perfect combination of luxury and practicality with our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets. Indulge in the sophistication and enduring beauty that comes with wearing premium quality jewelry. Elevate your accessory collection with these timeless bracelets, designed to be cherished for years to come.",
      description_list: [
        "Pure 18K Gold Plated",
        "Premium Quality Stainless Steel Base Metal",
        "Hypoallergenic, Lead & Nickel Free",
        "Anti-tarnish & Waterproof",
      ],
    },
    {
      name: "earrings",
      image: "../../assets/earrings/2/earrings_67_1080w.jpg",
      finish: "18K Gold",
      images: [
        "../../assets/earrings/2/earrings_62_1080w.jpg",
        "../../assets/earrings/2/earrings_63_1080w.jpg",
        "../../assets/earrings/2/earrings_64_1080w.jpg",
        "../../assets/earrings/2/earrings_65_1080w.jpg",
        "../../assets/earrings/2/earrings_66_1080w.jpg",
        "../../assets/earrings/2/earrings_67_1080w.jpg",
      ],
      images_thumb: [
        "../../assets/earrings/2/earrings_62_360w.jpg",
        "../../assets/earrings/2/earrings_63_360w.jpg",
        "../../assets/earrings/2/earrings_64_360w.jpg",
        "../../assets/earrings/2/earrings_65_360w.jpg",
        "../../assets/earrings/2/earrings_66_360w.jpg",
        "../../assets/earrings/2/earrings_67_360w.jpg",
      ],
      description: "Honey comb in Gold",
      description_details:
        "Moon by Sassyness Introducing our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets, where luxury meets durability. These exquisite bracelets are meticulously crafted to elevate your style with their timeless elegance and superior quality. Each bracelet is meticulously designed using high-grade 18k gold stainless steel, known for its exceptional resistance to tarnish and corrosion. With our anti-tarnish technology, your bracelet will maintain its stunning shine and brilliance, ensuring a long-lasting, lustrous appearance. Crafted with meticulous attention to detail, these bracelets showcase a refined and classy design that effortlessly complements any outfit. The sleek and polished surfaces exude sophistication, making them the perfect accessory for both formal occasions and everyday wear. Our premium 18k gold stainless steel material not only offers exceptional durability but also provides a hypoallergenic and skin-friendly option for those with sensitive skin. You can wear these bracelets with confidence, knowing they will withstand the test of time and maintain their exquisite beauty. The secure clasp ensures a comfortable and secure fit, allowing you to wear these bracelets with ease and confidence throughout the day. Whether you're attending a special event or adding a touch of elegance to your everyday ensemble, these bracelets are designed to make a statement. Experience the perfect combination of luxury and practicality with our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets. Indulge in the sophistication and enduring beauty that comes with wearing premium quality jewelry. Elevate your accessory collection with these timeless bracelets, designed to be cherished for years to come.",
      description_list: [
        "Pure 18K Gold Plated",
        "Premium Quality Stainless Steel Base Metal",
        "Hypoallergenic, Lead & Nickel Free",
        "Anti-tarnish & Waterproof",
      ],
    },
  ],
  necklace: [
    {
      name: "necklace",
      image: "../../assets/necklace/1/necklace_71_1080w.jpg",
      finish: "18K Gold",
      images: [
        "../../assets/necklace/1/necklace_69_1080w.jpg",
        "../../assets/necklace/1/necklace_70_1080w.jpg",
        "../../assets/necklace/1/necklace_71_1080w.jpg",
      ],
      images_thumb: [
        "../../assets/necklace/1/necklace_69_360w.jpg",
        "../../assets/necklace/1/necklace_70_360w.jpg",
        "../../assets/necklace/1/necklace_71_360w.jpg",
      ],
      description: "Rosette clover necklace",
      description_details:
        "Moon by Sassyness Introducing our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets, where luxury meets durability. These exquisite bracelets are meticulously crafted to elevate your style with their timeless elegance and superior quality. Each bracelet is meticulously designed using high-grade 18k gold stainless steel, known for its exceptional resistance to tarnish and corrosion. With our anti-tarnish technology, your bracelet will maintain its stunning shine and brilliance, ensuring a long-lasting, lustrous appearance. Crafted with meticulous attention to detail, these bracelets showcase a refined and classy design that effortlessly complements any outfit. The sleek and polished surfaces exude sophistication, making them the perfect accessory for both formal occasions and everyday wear. Our premium 18k gold stainless steel material not only offers exceptional durability but also provides a hypoallergenic and skin-friendly option for those with sensitive skin. You can wear these bracelets with confidence, knowing they will withstand the test of time and maintain their exquisite beauty. The secure clasp ensures a comfortable and secure fit, allowing you to wear these bracelets with ease and confidence throughout the day. Whether you're attending a special event or adding a touch of elegance to your everyday ensemble, these bracelets are designed to make a statement. Experience the perfect combination of luxury and practicality with our Classy Premium Anti-Tarnish 18k Gold Stainless Steel Bracelets. Indulge in the sophistication and enduring beauty that comes with wearing premium quality jewelry. Elevate your accessory collection with these timeless bracelets, designed to be cherished for years to come.",
      description_list: [
        "Pure 18K Gold Plated",
        "Premium Quality Stainless Steel Base Metal",
        "Hypoallergenic, Lead & Nickel Free",
        "Anti-tarnish & Waterproof",
      ],
    },
  ],
};
